echo '
<h4>Our Sponsors</h4>
<hr>
<a href="http://www.biparksfoundation.org/ " target="_blank" alt="BHS Sailing Team Supporter - Bainbridge Island Parks Foundation"> <img title="Bainbridge Island Parks Foundation" alt="BHS Sailing Team Supporter - Bainbridge Island Parks Foundation" src="http://bhssailing.net/wp-content/themes/BHS-Sailing/img/parks-min.jpg"><br><p>Bainbridge Island Parks Foundation</p></a>
<a href="http://www.bainbridgeislandrotary.org/" target="_blank" alt="BHS Sailing Team Supporter - Rotary Club of Bainbridge Island"><img title="Rotary Club of Bainbridge Island" alt="BHS Sailing Team Supporter - Rotary Club of Bainbridge Island" src="images/sponsors/rotary-min.jpg"><br><p>Rotary Club of Bainbridge Island</p></a>
<a href="http://www.eagleharboryachtclub.com/" target="_blank" alt="bhs sailing team supporter eagle harbor yacht club"><img title="Eagle Harbor Yacht Club" alt="BHS Sailing Team Supporter - Eagle Harbor Yacht Club" src="http://bhssailing.net/wp-content/themes/BHS-Sailing/img/eagleharboryc-min.gif"><br><p>Eagle Harbor Yacht Club</p></a>
<a href="http://www.spartanboosteralumniclub.org/" target="_blank" alt="bhs sailing team supporter spartan boooster alumni club"><img title="Spartan Boooster Alumni Club" alt="BHS Sailing Team Supporter - Spartan Boooster Alumni Club" src="http://bhssailing.net/wp-content/themes/BHS-Sailing/img/spartan-min.jpg"><br><p>Spartan Boooster Alumni Club</p></a>
<a href="http://portmadisonyc.org/" target="_blank" alt="bhs sailing team supporter port madison yacht club"> <img title="Port Madison Yacht Club" alt="BHS Sailing Team Supporter - Port Madison Yacht Club" src="http://bhssailing.net/wp-content/themes/BHS-Sailing/img/pmyc-min.jpg"><br><p>Port Madison Yacht Club</p></a>
<a href="http://www.thesailingfoundation.org/" target="_blank" alt="BHS Sailing Team Supporter - The Sailing Foundation"> <img title="The Sailing Foundation" alt="BHS Sailing Team Supporter - The Sailing Foundation" src="http://bhssailing.net/wp-content/themes/BHS-Sailing/img/tsf.png"><br><p>The Sailing Foundation</p></a>
<a href="http://www.onecallforall.org/" target="_blank" alt="BHS Sailing Team Supporter - One Call For All"> <img title="One Call For All" alt="BHS Sailing Team Supporter - One Call For All" src="http://bhssailing.net/wp-content/themes/BHS-Sailing/img/ocfa_logo.gif"> <br><p>One Call For All</p></a>
<a href="http://bainbridgecf.org/" target="_blank" alt="BHS Sailing Team Supporter - Bainbridge Community Foundation"> <img title="Bainbridge Community Foundation" alt="BHS Sailing Team Supporter - Bainbridge Community Foundation" src="http://bhssailing.net/wp-content/themes/BHS-Sailing/img/image05.jpg"><br><p>Bainbridge Community Foundation</p></a>
<a href="http://www.sycfoundation.org/" target="_blank" alt="BHS Sailing Team Supporter - SYC Foundation"> <img title="SYC Foundation" alt="BHS Sailing Team Supporter - SYC Foundation" src="http://bhssailing.net/wp-content/themes/BHS-Sailing/img/image07.jpg"><br><p>SYC Foundation</p></a>
<p>(c) 2016 Harrison Saliba</p>
'